#!/usr/bin/env bash
(
cat <<'EOF'
# Overview

## Section 1.1

### Section 1.1.1 ###
### Section 1.1.2 ##

## Section 1.2
## Section 1.3

Hello `world`, this is a block of code here…

```
<?php

    phpinfo();

```
EOF
) | ./mtj